/**
 *
 * LB-LMC based Circuit Solver Engine
 *
 * Auto-generated by SolverEngineGenerator Object of the ORTiS Circuit Solver Codegen Tools
 *
 */

#ifndef shipboard_zonal_system_SIMULATIONENGINE_HPP
#define shipboard_zonal_system_SIMULATIONENGINE_HPP

typedef float real;

//template< int instance, typename real >
void shipboard_zonal_system_solver
(
real x_out[56],
real * cp_voltage_dcdc1,
real * cn_voltage_dcdc1,
real * la_current_dcdc1,
real * lb_current_dcdc1,
real * lc_current_dcdc1,
real * cp_voltage_dcdc2,
real * cn_voltage_dcdc2,
real * la_current_dcdc2,
real * lb_current_dcdc2,
real * lc_current_dcdc2,
real* l_current_cable_l01,
real* l_current_cable_l02,
real* l_current_cable_l03,
real* l_current_cable_l04,
real* l_current_cable_l05,
real* l_current_cable_l06,
real* l_current_cable_l07,
real* l_current_cable_l08,
real* l_current_cable_l09,
real* l_current_cable_l10,
real* l_current_cable_l11,
real* l_current_cable_l12,
real* l_current_cable_l13,
real* l_current_cable_l14,
real* l_current_cable_l15,
real* l_current_cable_l16,
real * cp_voltage_inv1,
real * cn_voltage_inv1,
real * la_current_inv1,
real * lb_current_inv1,
real * lc_current_inv1,
real * cp_voltage_inv2,
real * cn_voltage_inv2,
real * la_current_inv2,
real * lb_current_inv2,
real * lc_current_inv2,
real * cp_voltage_inv3,
real * cn_voltage_inv3,
real * la_current_inv3,
real * lb_current_inv3,
real * lc_current_inv3,
real * cp_voltage_inv4,
real * cn_voltage_inv4,
real * la_current_inv4,
real * lb_current_inv4,
real * lc_current_inv4,
real * cp_voltage_inv5,
real * cn_voltage_inv5,
real * la_current_inv5,
real * lb_current_inv5,
real * lc_current_inv5,
real * cp_voltage_inv6,
real * cn_voltage_inv6,
real * la_current_inv6,
real * lb_current_inv6,
real * lc_current_inv6,
bool sw_ctrl_dcdc1[3],
bool sw_en_dcdc1,
bool sw_ctrl_dcdc2[3],
bool sw_en_dcdc2,
bool sw_ctrl_inv1[3],
bool sw_en_inv1,
bool sw_ctrl_inv2[3],
bool sw_en_inv2,
bool sw_ctrl_inv3[3],
bool sw_en_inv3,
bool sw_ctrl_inv4[3],
bool sw_en_inv4,
bool sw_ctrl_inv5[3],
bool sw_en_inv5,
bool sw_ctrl_inv6[3],
bool sw_en_inv6
);

#endif
